sudo: false
language : node_js
node_js:
  - "0.12"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++-4.8
      - g++-5
matrix:
  include:
    - compiler: gcc
      env: CXX=g++-4.8
    - compiler: gcc
      env: CXX=g++-5
before_install:
  - g++ --version
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
